service: global-storage-lambdaedge
frameworkVersion: '3'

provider:
  name: aws
  stackTags:
    Product: 'marketboro'
    Service: 'marketboro-global-storage-lambdaedge'
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30
  deploymentBucket:
    name: ${self:custom.envVar.s3DeployBucketName}
    serverSideEncryption: aws:kms
    sseKMSKeyId: alias/aws/s3
  iam:
    role: ${self:custom.envVar.roleArn}
  logRetentionInDays: ${self:custom.envVar.logRetentionInDays}

custom:
  stage: ${opt:stage, 'dev'}
  envVar: ${file(./config/config.${opt:stage, 'dev'}.json)}
  prune:
    automatic: true
    includeLayers: true
    number: 3

plugins:
  - serverless-deployment-bucket
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies
  - serverless-prune-versions
  - serverless-plugin-resource-tagging


package:
  excludeDevDependencies: false
  patterns:
    - '!config/**'
    - '!node_modules/**'
    - '!README.md'
    - '!.idea'

functions:
  storage-images-resize:
    tags:
      Resource: 'global-storage-lambdaedge-lambda'
    handler: src/functions/storage-images-resize.handler
    memorySize: 1536
  storage-not-found-response:
    tags:
      Resource: 'global-storage-lambdaedge-lambda'
    handler: src/functions/storage-not-found-response.handler
