service: global-storage-lambdaedge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  deploymentBucket:
    name: ${self:custom.envVar.s3DeployBucketName}
    serverSideEncryption: aws:kms
    sseKMSKeyId: alias/aws/s3
  iam:
    role: ${self:custom.envVar.roleArn}
  logRetentionInDays: ${self:custom.envVar.logRetentionInDays}
custom:
  stage: ${opt:stage, 'dev'}
  envVar: ${file(./config/config.${opt:stage, 'dev'}.json)}

plugins:
  - serverless-deployment-bucket
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies

package:
  excludeDevDependencies: false
  patterns:
    - '!config/**'
    - '!node_modules/**'
    - '!README.md'
    - '!.idea'

functions:
  storage-images-resize:
    handler: src/functions/storage-images-resize.handler
    timeout: 30
    memorySize: 1536
  storage-not-found-response:
    handler: src/functions/storage-not-found-response.handler
    timeout: 30
